-- ====================================================================
-- SQL Script: Create "orders" Table for Golden Circle Hair Growth
-- ====================================================================
-- How to apply this schema:
-- 1. Go to your Supabase Dashboard: https://supabase.com
-- 2. Select your project: "pluhjzrozhfkyzbuwqij"
-- 3. In the left navigation, click on "SQL Editor"
-- 4. Click "+ New Query"
-- 5. Paste the entire contents of this file into the editor
-- 6. Click "Run" at the bottom right
-- ====================================================================

-- 1. Create the orders table if it doesn't already exist
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    city TEXT NOT NULL,
    address TEXT,
    bundle_id TEXT,
    bundle_name TEXT,
    quantity INTEGER DEFAULT 1,
    total_price INTEGER,
    notes TEXT,
    status TEXT DEFAULT 'Nouveau' NOT NULL
);

-- 2. Enable Row Level Security (RLS) to secure the data
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Create a Row Level Security policy to allow insertions from the app (using anon key)
CREATE POLICY "Allow anyone to insert orders" 
ON public.orders 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 4. Create a Row Level Security policy to allow selecting orders
CREATE POLICY "Allow public select for dashboard sync" 
ON public.orders 
FOR SELECT 
TO anon 
USING (true);

-- 5. Create a Row Level Security policy to allow updates (e.g. changing order status)
CREATE POLICY "Allow public update for status changes" 
ON public.orders 
FOR UPDATE 
TO anon 
USING (true)
WITH CHECK (true);
